/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SablonRouteImport } from './routes/sablon'
import { Route as MagazaStoreIdRouteImport } from './routes/magaza.$storeId'
import { Route as RaporVisitIdRouteImport } from './routes/rapor.$visitId'
import { Route as ZiyaretVisitIdRouteImport } from './routes/ziyaret.$visitId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SablonRoute = SablonRouteImport.update({
  id: '/sablon',
  path: '/sablon',
  getParentRoute: () => rootRouteImport,
} as any)
const MagazaStoreIdRoute = MagazaStoreIdRouteImport.update({
  id: '/magaza/$storeId',
  path: '/magaza/$storeId',
  getParentRoute: () => rootRouteImport,
} as any)
const RaporVisitIdRoute = RaporVisitIdRouteImport.update({
  id: '/rapor/$visitId',
  path: '/rapor/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)
const ZiyaretVisitIdRoute = ZiyaretVisitIdRouteImport.update({
  id: '/ziyaret/$visitId',
  path: '/ziyaret/$visitId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sablon': typeof SablonRoute
  '/magaza/$storeId': typeof MagazaStoreIdRoute
  '/rapor/$visitId': typeof RaporVisitIdRoute
  '/ziyaret/$visitId': typeof ZiyaretVisitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sablon': typeof SablonRoute
  '/magaza/$storeId': typeof MagazaStoreIdRoute
  '/rapor/$visitId': typeof RaporVisitIdRoute
  '/ziyaret/$visitId': typeof ZiyaretVisitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sablon': typeof SablonRoute
  '/magaza/$storeId': typeof MagazaStoreIdRoute
  '/rapor/$visitId': typeof RaporVisitIdRoute
  '/ziyaret/$visitId': typeof ZiyaretVisitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sablon'
    | '/magaza/$storeId'
    | '/rapor/$visitId'
    | '/ziyaret/$visitId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sablon'
    | '/magaza/$storeId'
    | '/rapor/$visitId'
    | '/ziyaret/$visitId'
  id:
    | '__root__'
    | '/'
    | '/sablon'
    | '/magaza/$storeId'
    | '/rapor/$visitId'
    | '/ziyaret/$visitId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SablonRoute: typeof SablonRoute
  MagazaStoreIdRoute: typeof MagazaStoreIdRoute
  RaporVisitIdRoute: typeof RaporVisitIdRoute
  ZiyaretVisitIdRoute: typeof ZiyaretVisitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sablon': {
      id: '/sablon'
      path: '/sablon'
      fullPath: '/sablon'
      preLoaderRoute: typeof SablonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/magaza/$storeId': {
      id: '/magaza/$storeId'
      path: '/magaza/$storeId'
      fullPath: '/magaza/$storeId'
      preLoaderRoute: typeof MagazaStoreIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rapor/$visitId': {
      id: '/rapor/$visitId'
      path: '/rapor/$visitId'
      fullPath: '/rapor/$visitId'
      preLoaderRoute: typeof RaporVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ziyaret/$visitId': {
      id: '/ziyaret/$visitId'
      path: '/ziyaret/$visitId'
      fullPath: '/ziyaret/$visitId'
      preLoaderRoute: typeof ZiyaretVisitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SablonRoute: SablonRoute,
  MagazaStoreIdRoute: MagazaStoreIdRoute,
  RaporVisitIdRoute: RaporVisitIdRoute,
  ZiyaretVisitIdRoute: ZiyaretVisitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
